POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ./input.png

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

user_album
------FormBoundary1234


### GET - pobierz wszystkie dane
GET http://localhost:3000/api/photos HTTP/1.1


### DELETE - usuń wg id
DELETE http://localhost:3000/api/photos/1712664982600 HTTP/1.1

### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/photos/1713270500314 HTTP/1.1

{
"test": "dzik",
"dest": 12343352
}


