####
GET http://localhost:3000/api/filters/metadata/1716734482486 HTTP/1.1

####
GET http://localhost:3000/api/getimage/1717977475030 HTTP/1.1

#####

PATCH http://localhost:3000/api/filters HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNzk3NzMyNzI4NCwiaWF0IjoxNzE3OTc3MzI3LCJleHAiOjE3MTc5ODgxMjd9.k04PMF3byYLgRn6sZ1Qbi8oHmghHbHhVk4XPCriAcLQ

{   
  "id":1717977475030,
  "filter": "negate",
  "rotate": 157,
  "rgb": {"r": 23, "g": 20, "b": 50},
  "size": {"width": 50, "height": 50, "top": 0, "left": 0}
}

####
GET http://localhost:3000/api/getimage/1716734482486/filter/negate HTTP/1.1



