POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ./w.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

user_album
------FormBoundary1234


### GET - pobierz wszystkie dane
GET http://localhost:3000/api/photos HTTP/1.1


### DELETE - usuń wg id
DELETE http://localhost:3000/api/photos/1716291262776 HTTP/1.1

### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/photos/1716291262776 HTTP/1.1

{
"test": "dzik",
"dest": 12343352
}

### dodanie jednego taga

PATCH http://localhost:3000/api/photos/tags/1716370712173 HTTP/1.1

{
    "value": "#kekw"
}

######## dodanie wielu tagów

PATCH http://localhost:3000/api/photos/tags/mass/1716370712173 HTTP/1.1

{
    "value": ["#raz", "#dwa"]
}


