POST http://localhost:3000/api/photos HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNzkzOTk2MTkyMiwiaWF0IjoxNzE3OTM5OTYxLCJleHAiOjE3MTc5NDExNjF9.i7AOfiKCpjULPWDzoGiAwL_SRne7cneZhKlhTlqpiVs
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ./w.jpg

------FormBoundary1234


### GET - pobierz wszystkie dane
GET http://localhost:3000/api/photos HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNjczNDM1MzM5OCwiaWF0IjoxNzE2NzM0MzUzLCJleHAiOjE3MTY3MzU1NTN9.ht4CdAYOOWFZybuS7EmV098BV6zhnY1SjXwoozwGInY


### DELETE - usuń wg id
DELETE http://localhost:3000/api/photos/1716734482486 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNjczNDM1MzM5OCwiaWF0IjoxNzE2NzM0MzUzLCJleHAiOjE3MTY3MzU1NTN9.ht4CdAYOOWFZybuS7EmV098BV6zhnY1SjXwoozwGInY


### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/photos/1717614803818 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNzYxNDc4NjMxNiwiaWF0IjoxNzE3NjE0Nzg2LCJleHAiOjE3MTc2MTU5ODZ9.A0atS1nsAS_7-8OqnP062ZHh2BSzwa0hS_xKIjSvRAQ

{
"test": "dzik",
"dest": 12343352
}

### dodanie jednego taga

PATCH http://localhost:3000/api/photos/tags/1716734482486 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNjczNDM1MzM5OCwiaWF0IjoxNzE2NzM0MzUzLCJleHAiOjE3MTY3MzU1NTN9.ht4CdAYOOWFZybuS7EmV098BV6zhnY1SjXwoozwGInY

{
    "value": "#kekw"
}

######## dodanie wielu tagów

PATCH http://localhost:3000/api/photos/tags/mass/1716734482486 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNjczNDM1MzM5OCwiaWF0IjoxNzE2NzM0MzUzLCJleHAiOjE3MTY3MzU1NTN9.ht4CdAYOOWFZybuS7EmV098BV6zhnY1SjXwoozwGInY

{
    "value": ["#raz", "#dwa"]
}


