GET http://localhost:3000/api/profile/asd HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamFuIiwiZW1haWwiOiJkQHMucGwiLCJ0aW1lc3RhbXAiOjE3MTc5NTQ4NTQ5OTUsImlhdCI6MTcxNzk1NDg1NCwiZXhwIjoxNzE3OTU2MDU0fQ.43NwoGccVnmcwBdPQM-O1tmDQtOyeX_AED19XglgV90
###
GET http://localhost:3000/api/profile/picture/a@b.pl HTTP/1.1



####
PATCH http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamFuIiwiZW1haWwiOiJkQHMucGwiLCJ0aW1lc3RhbXAiOjE3MTc5NTQ4NTQ5OTUsImlhdCI6MTcxNzk1NDg1NCwiZXhwIjoxNzE3OTU2MDU0fQ.43NwoGccVnmcwBdPQM-O1tmDQtOyeX_AED19XglgV90


{
    "name": "romek",
    "lastName": "Wesoly"
}

#####profilowe
POST http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRhbSIsImVtYWlsIjoiYUBiLnBsIiwidGltZXN0YW1wIjoxNzE3OTY1MDMxNzExLCJpYXQiOjE3MTc5NjUwMzEsImV4cCI6MTcxNzk2NjIzMX0.iv1T1lk_2s0bMDRA96RnZS4g6rmCI1O_-Up-3QKg64o
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ./w.jpg

------FormBoundary1234
####
GET http://localhost:3000/api/logout HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNjczNDM1MzM5OCwiaWF0IjoxNzE2NzM0MzUzLCJleHAiOjE3MTY3MzU1NTN9.ht4CdAYOOWFZybuS7EmV098BV6zhnY1SjXwoozwGInY



