GET http://localhost:3000/api/user HTTP/1.1

###
POST http://localhost:3000/api/user/register HTTP/1.1

{    
   "name": "name",
   "lastName": "lastName",
   "email":"name@email.pl",
   "password":"password"
}

####

POST http://localhost:3000/api/user/login HTTP/1.1 

{
  "email":"name@email.pl",
  "password":"password"
}


####
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZSIsImVtYWlsIjoibmFtZUBlbWFpbC5wbCIsInRpbWVzdGFtcCI6MTcxNzk3NzMyNzI4NCwiaWF0IjoxNzE3OTc3MzI3LCJleHAiOjE3MTc5ODgxMjd9.k04PMF3byYLgRn6sZ1Qbi8oHmghHbHhVk4XPCriAcLQ





